// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

/* Imports *******/
import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {ERC721URIStorage} from "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

/* Events ********/

/* Errors ********/

/* Interfaces ****/

import {IProofNFT} from "./interfaces/IProofNFT.sol";

/* Libraries *****/

/**
 * @title ProofNFT
 * @author BTBMan
 * @notice ERC721 credential minted from an employee-controlled salary proof.
 * @dev This contract deliberately contains no FHE logic. SalaryProof owns proof validity and is the only minter.
 */
contract ProofNFT is IProofNFT, ERC721URIStorage, Ownable {
    ////////////////////////////////////
    // Type declarations              //
    ////////////////////////////////////

    ////////////////////////////////////
    // State variables                //
    ////////////////////////////////////
    // Next token identifier to mint. Zero is reserved as an unset sentinel.
    uint256 public nextTokenId;
    // SalaryProof contract authorized to mint proof credentials.
    address public salaryProofContract;

    // Maps an NFT token id back to the source salary proof id.
    mapping(uint256 tokenId => uint256 proofId) public tokenProofIds;
    // Maps one salary proof id to its minted token id. Zero means not minted.
    mapping(uint256 proofId => uint256 tokenId) public proofTokenIds;

    ////////////////////////////////////
    // Modifiers                      //
    ////////////////////////////////////

    constructor()
        ERC721("SalaryCipher Salary Proof", "scPROOF")
        Ownable(msg.sender)
    {
        nextTokenId = 1;
    }

    ////////////////////////////////////
    // Receive & Fallback             //
    ////////////////////////////////////

    ////////////////////////////////////
    // Functions                      //
    ////////////////////////////////////
    /**
     * @notice Configures the only contract allowed to mint proof NFTs.
     * @dev Kept as a setter to avoid a circular deployment dependency between ProofNFT and SalaryProof.
     * @param salaryProofContract_ The deployed SalaryProof contract address.
     */
    function setSalaryProofContract(
        address salaryProofContract_
    ) external onlyOwner {
        if (salaryProofContract_ == address(0)) {
            revert ProofNFT__InvalidAddress();
        }

        salaryProofContract = salaryProofContract_;

        emit SalaryProofContractUpdated(salaryProofContract_);
    }

    /**
     * @notice Mints one NFT credential for a salary proof.
     * @dev A proof id can be minted only once. SalaryProof remains the source of truth for proof status.
     * @param to The employee wallet receiving the credential.
     * @param proofId The source SalaryProof proof id.
     * @param metadataURI IPFS metadata URI generated by the frontend.
     * @return tokenId The minted ERC721 token id.
     */
    function mint(
        address to,
        uint256 proofId,
        string calldata metadataURI
    ) external returns (uint256 tokenId) {
        if (msg.sender != salaryProofContract) {
            revert ProofNFT__OnlySalaryProof();
        }
        if (to == address(0)) {
            revert ProofNFT__InvalidAddress();
        }
        if (bytes(metadataURI).length == 0) {
            revert ProofNFT__InvalidTokenURI();
        }
        if (proofTokenIds[proofId] != 0) {
            revert ProofNFT__ProofAlreadyMinted();
        }

        tokenId = nextTokenId++;
        proofTokenIds[proofId] = tokenId;
        tokenProofIds[tokenId] = proofId;

        _safeMint(to, tokenId);
        _setTokenURI(tokenId, metadataURI);

        emit ProofNFTMinted(proofId, tokenId, to, metadataURI);
    }

    ////////////////////////////////////
    // Getter functions               //
    ////////////////////////////////////
}
