// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

/* Imports *******/
import {FHE, ebool, euint128, externalEuint128} from "@fhevm/solidity/lib/FHE.sol";
import {ZamaEthereumConfig} from "@fhevm/solidity/config/ZamaConfig.sol";

/* Events ********/

/* Errors ********/

/* Interfaces ****/
import {ICompanyRegistry} from "./interfaces/ICompanyRegistry.sol";
import {ISalaryCipherCore} from "./interfaces/ISalaryCipherCore.sol";
import {ProofNFT} from "./ProofNFT.sol";
import {ISalaryProof} from "./interfaces/ISalaryProof.sol";

/* Libraries *****/
import {DateTimeLib} from "solady/src/utils/DateTimeLib.sol";

/**
 * @title SalaryProof
 * @author BTBMan
 * @notice Manages employee-controlled private salary proofs and optional RWA NFT minting.
 * @dev Salary comparisons stay inside SalaryCipherCore; this contract stores only encrypted boolean proof results.
 */
contract SalaryProof is ISalaryProof, ZamaEthereumConfig {
    ////////////////////////////////////
    // Type declarations              //
    ////////////////////////////////////
    using DateTimeLib for uint256;

    ////////////////////////////////////
    // State variables                //
    ////////////////////////////////////
    // Registry used as the source of company roles and employee start dates.
    ICompanyRegistry public immutable companyRegistry;
    // Payroll core used to compare encrypted monthly salary values.
    ISalaryCipherCore public immutable salaryCipherCore;
    // ERC721 credential contract used for optional RWA proof minting.
    ProofNFT public immutable proofNFT;
    // Next proof identifier to assign. Zero is reserved as an unset sentinel.
    uint256 public nextProofId;

    // Public proof records indexed by proof id.
    mapping(uint256 proofId => Proof proof) public proofs;
    // Proof ids generated by one employee in one company.
    mapping(uint256 companyId => mapping(address employee => uint256[] proofIds))
        private employeeProofIds;
    // Third-party verifier authorization by proof id and verifier address.
    mapping(uint256 proofId => mapping(address verifier => bool authorized))
        public authorizedVerifiers;

    ////////////////////////////////////
    // Modifiers                      //
    ////////////////////////////////////

    /**
     * @notice Creates the salary proof coordinator.
     * @param companyRegistryAddress The deployed CompanyRegistry contract address.
     * @param salaryCipherCoreAddress The deployed SalaryCipherCore contract address.
     * @param proofNFTAddress The deployed ProofNFT contract address.
     */
    constructor(
        address companyRegistryAddress,
        address salaryCipherCoreAddress,
        address proofNFTAddress
    ) {
        if (
            companyRegistryAddress == address(0) ||
            salaryCipherCoreAddress == address(0) ||
            proofNFTAddress == address(0)
        ) {
            revert SalaryProof__InvalidAddress();
        }

        companyRegistry = ICompanyRegistry(companyRegistryAddress);
        salaryCipherCore = ISalaryCipherCore(salaryCipherCoreAddress);
        proofNFT = ProofNFT(proofNFTAddress);
        nextProofId = 1;
    }

    ////////////////////////////////////
    // Receive & Fallback             //
    ////////////////////////////////////

    ////////////////////////////////////
    // Functions                      //
    ////////////////////////////////////
    /**
     * @notice Generates one employee-owned salary proof.
     * @dev The caller is always the proof owner. Owner role is excluded by design from personal salary proofs.
     * @param companyId The company namespace.
     * @param proofType The fixed proof type to generate.
     * @param encryptedMin Minimum encrypted salary threshold for MONTHLY_GTE and MONTHLY_BETWEEN.
     * @param encryptedMax Maximum encrypted salary threshold for MONTHLY_BETWEEN.
     * @param inputProof FHE input proof for encryptedMin / encryptedMax.
     * @param durationMonths Required employment duration for EMPLOYMENT_DURATION_GTE.
     * @param validityDays Number of days before this proof expires.
     * @return proofId The newly generated proof id.
     */
    function generateProof(
        uint256 companyId,
        ProofType proofType,
        externalEuint128 encryptedMin,
        externalEuint128 encryptedMax,
        bytes calldata inputProof,
        uint32 durationMonths,
        uint32 validityDays
    ) external returns (uint256 proofId) {
        _requireProofOwnerRole(companyId, msg.sender);
        if (validityDays == 0) {
            revert SalaryProof__InvalidValidity();
        }

        ebool result = _generateProofResult(
            companyId,
            msg.sender,
            proofType,
            encryptedMin,
            encryptedMax,
            inputProof,
            durationMonths
        );

        proofId = nextProofId++;
        uint64 createdAt = _blockTimestamp();
        uint64 expiresAt = createdAt + uint64(validityDays) * uint64(1 days);

        proofs[proofId] = Proof({
            companyId: companyId,
            employee: msg.sender,
            proofType: proofType,
            result: result,
            createdAt: createdAt,
            expiresAt: expiresAt,
            revoked: false,
            minted: false,
            tokenId: 0
        });
        employeeProofIds[companyId][msg.sender].push(proofId);

        FHE.allowThis(result);
        FHE.allow(result, msg.sender);

        emit ProofGenerated(
            proofId,
            companyId,
            msg.sender,
            proofType,
            expiresAt
        );
    }

    /**
     * @notice Grants a third party permission to decrypt one proof result.
     * @dev Authorization only affects the encrypted result handle, not the employee salary itself.
     * @param proofId The proof id to authorize.
     * @param verifier The third-party verifier wallet.
     */
    function authorizeVerifier(uint256 proofId, address verifier) external {
        Proof storage proof = _requireOwnedProof(proofId, msg.sender);
        _requireActiveProof(proof);
        if (verifier == address(0)) {
            revert SalaryProof__InvalidAddress();
        }

        authorizedVerifiers[proofId][verifier] = true;
        FHE.allow(proof.result, verifier);

        emit VerifierAuthorized(proofId, verifier);
    }

    /**
     * @notice Revokes one proof so third parties should no longer accept it.
     * @param proofId The proof id to revoke.
     */
    function revokeProof(uint256 proofId) external {
        Proof storage proof = _requireOwnedProof(proofId, msg.sender);
        if (proof.revoked) {
            revert SalaryProof__ProofRevoked();
        }

        proof.revoked = true;

        emit ProofRevoked(proofId);
    }

    /**
     * @notice Mints one active proof as an ERC721 RWA credential.
     * @dev The encrypted result is not publicly decrypted on-chain; verifiers must still inspect proof status and decrypt if authorized.
     * @param proofId The proof id to mint.
     * @param tokenURI IPFS metadata URI generated by the frontend.
     * @return tokenId The minted ERC721 token id.
     */
    function mintProofNFT(
        uint256 proofId,
        string calldata tokenURI
    ) external returns (uint256 tokenId) {
        Proof storage proof = _requireOwnedProof(proofId, msg.sender);
        _requireActiveProof(proof);
        if (proof.minted) {
            revert SalaryProof__ProofAlreadyMinted();
        }
        if (bytes(tokenURI).length == 0) {
            revert SalaryProof__InvalidTokenURI();
        }

        tokenId = proofNFT.mint(msg.sender, proofId, tokenURI);
        proof.minted = true;
        proof.tokenId = tokenId;

        emit ProofNFTMinted(proofId, tokenId);
    }

    /// @dev Creates the encrypted result for the selected proof type.
    function _generateProofResult(
        uint256 companyId,
        address employee,
        ProofType proofType,
        externalEuint128 encryptedMin,
        externalEuint128 encryptedMax,
        bytes calldata inputProof,
        uint32 durationMonths
    ) private returns (ebool) {
        if (proofType == ProofType.MONTHLY_GTE) {
            euint128 minThreshold = FHE.fromExternal(encryptedMin, inputProof);
            FHE.allow(minThreshold, address(salaryCipherCore));
            return
                _normalizeBool(
                    salaryCipherCore.verifySalaryCondition(
                        companyId,
                        employee,
                        ISalaryCipherCore.ConditionType.GTE,
                        minThreshold
                    )
                );
        }

        if (proofType == ProofType.MONTHLY_BETWEEN) {
            euint128 minThreshold = FHE.fromExternal(encryptedMin, inputProof);
            euint128 maxThreshold = FHE.fromExternal(encryptedMax, inputProof);
            FHE.allow(minThreshold, address(salaryCipherCore));
            FHE.allow(maxThreshold, address(salaryCipherCore));

            ebool aboveMin = salaryCipherCore.verifySalaryCondition(
                companyId,
                employee,
                ISalaryCipherCore.ConditionType.GTE,
                minThreshold
            );
            ebool belowMax = salaryCipherCore.verifySalaryCondition(
                companyId,
                employee,
                ISalaryCipherCore.ConditionType.LTE,
                maxThreshold
            );

            return
                _normalizeBool(
                    FHE.select(aboveMin, belowMax, FHE.asEbool(false))
                );
        }

        if (proofType == ProofType.EMPLOYMENT_DURATION_GTE) {
            if (durationMonths == 0) {
                revert SalaryProof__InvalidDuration();
            }

            ICompanyRegistry.Employee memory employeeInfo = companyRegistry
                .getEmployee(companyId, employee);
            uint256 eligibleAt = uint256(employeeInfo.addedAt).addMonths(
                durationMonths
            );

            return
                _normalizeBool(
                    FHE.ge(
                        FHE.asEuint128(uint128(block.timestamp)),
                        uint128(eligibleAt)
                    )
                );
        }

        revert SalaryProof__InvalidProofType();
    }

    /// @dev Converts comparison output into an initialized decryptable encrypted boolean.
    function _normalizeBool(ebool value) private returns (ebool) {
        return FHE.select(value, FHE.asEbool(true), FHE.asEbool(false));
    }

    /// @dev Reverts unless the account is HR or Employee in the selected company.
    function _requireProofOwnerRole(
        uint256 companyId,
        address account
    ) private view {
        ICompanyRegistry.Role role = companyRegistry.getRole(
            companyId,
            account
        );
        if (
            role != ICompanyRegistry.Role.HR &&
            role != ICompanyRegistry.Role.Employee
        ) {
            revert SalaryProof__Unauthorized();
        }
    }

    /// @dev Reverts unless the proof exists and belongs to the supplied account.
    function _requireOwnedProof(
        uint256 proofId,
        address account
    ) private view returns (Proof storage proof) {
        proof = proofs[proofId];
        if (proof.employee == address(0)) {
            revert SalaryProof__ProofDoesNotExist();
        }
        if (proof.employee != account) {
            revert SalaryProof__Unauthorized();
        }
    }

    /// @dev Reverts when a proof is expired or revoked.
    function _requireActiveProof(Proof storage proof) private view {
        if (proof.revoked) {
            revert SalaryProof__ProofRevoked();
        }
        if (block.timestamp > proof.expiresAt) {
            revert SalaryProof__ProofExpired();
        }
    }

    /// @dev Returns the current block timestamp in the compact type used by storage.
    function _blockTimestamp() private view returns (uint64) {
        return uint64(block.timestamp);
    }

    ////////////////////////////////////
    // Getter functions               //
    ////////////////////////////////////
    /**
     * @notice Returns all proof ids generated by one employee in one company.
     * @param companyId The company namespace.
     * @param employee The employee account.
     * @return proofIds The generated proof ids.
     */
    function getEmployeeProofIds(
        uint256 companyId,
        address employee
    ) external view returns (uint256[] memory proofIds) {
        return employeeProofIds[companyId][employee];
    }

    /**
     * @notice Returns public proof status without decrypting the encrypted result.
     * @param proofId The proof id to inspect.
     * @return valid Whether the proof exists, is not expired, and is not revoked.
     * @return expired Whether the proof has passed its expiry timestamp.
     * @return revoked Whether the employee revoked the proof.
     */
    function verifyProof(
        uint256 proofId
    ) external view returns (bool valid, bool expired, bool revoked) {
        Proof storage proof = proofs[proofId];
        if (proof.employee == address(0)) {
            revert SalaryProof__ProofDoesNotExist();
        }

        expired = block.timestamp > proof.expiresAt;
        revoked = proof.revoked;
        valid = !expired && !revoked;
    }
}
